name: 02 - workflow Events

on: 
  push:
  pull_request:
  schedule:
     - cron: '*/5 * * * *''
  workflow_dispatch:


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "I've been triggered by a() ${{ github.event_name}} event."
